<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Post\Module'                        => __DIR__ . '/Module.php',
    'Post\Controller\IndexController' => __DIR__ . '/src/Post/Controller/IndexController.php',
    'PostTest\Framework\TestCase'        => __DIR__ . '/tests/Post/Framework/TestCase.php',
    'PostTest\SampleTest'                => __DIR__ . '/tests/Post/SampleTest.php',
);
