<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Team\Module'                        => __DIR__ . '/Module.php',
    'Team\Controller\IndexController' => __DIR__ . '/src/Team/Controller/IndexController.php',
    'TeamTest\Framework\TestCase'        => __DIR__ . '/tests/Team/Framework/TestCase.php',
    'TeamTest\SampleTest'                => __DIR__ . '/tests/Team/SampleTest.php',
);
