<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sVacation Forecasting Application%s'), '<span class="zf-green">', '</span>') ?></h1>
    <div class="control-group">
        <p><a
              class="btn btn-primary btn-lg" id="login-yammer" role="button" onclick="logInUser()"><?php echo $this->translate('Login through Yammer!') ?> &raquo;</a></p>
    </div>
</div>
