<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Dashboard\Module'                        => __DIR__ . '/Module.php',
    'Dashboard\Controller\IndexController' => __DIR__ . '/src/Dashboard/Controller/IndexController.php',
    'DashboardTest\Framework\TestCase'        => __DIR__ . '/tests/Dashboard/Framework/TestCase.php',
    'DashboardTest\SampleTest'                => __DIR__ . '/tests/Dashboard/SampleTest.php',
);
