<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="error-box">
<!--       <div class="message-small">Whoa! What are you doing here?</div> -->
      <div class="message-big">404</div>
      <div class="message-small">You are not where you're supposed to be</div>

      <div style="margin-top: 50px">
        <a class="btn btn-blue" href="<?php echo $this->url('dashboard', array(
        				'action' =>  'index'));?>">
            <i class="icon-arrow-left"></i> Back to dashboard
        </a>
      </div>
    </div>
  </div>
</div>