  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
    <div class="widget widget-profile">
    <div class="widget-header clearfix">
    	<span class="pull-left"><i class="icon-user-male"></i> Mini Profile</span>
    	<div class="dropdown pull-right">
    		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog-2"></i> <b class="caret"></b></a>
    		<ul class="dropdown-menu">
                <li><a href="typography.html">Typography</a></li>
    			<li><a href="forms.html">Forms</a></li>
    			<li><a href="ui.html">UI Elements</a></li>
    			<li><a href="tables.html">Tables</a></li>
    			<li><a href="charts.html">Charts</a></li>
    			<li><a href="calendar.html">Calendars</a></li>
            </ul>
    	</div>
    </div>
    <div class="profile-head bg-color dark-blue rounded-top">
    	<div class="box-padding">
    		<img class="avatar img-circle" src="img/styler/dummy/margaery.jpg">
    		<h3 class="normal">Maergery Tyrell</h3>
  </div>
 </div>
 </div>
 </div>
    