 <div class="row">
   <div class="col-lg-12">
    <div class="pull-left">
        <h1>Good Morning Ryan</h1>
    </div>
    </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Dashboard</li>
    <li><a href="index.html" class="text-transparent">Teams</a></li>
    <li class="active"><a href="index.html" class="text-transparent">Hercules</a></li>
    </ol>
  </div>
</div>
<div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-info"  id="dashBoardPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-dashboard fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Dashboard</p>
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-warning"  id="productivityPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-bar-chart-o fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Productivity</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-danger"  id="calendarPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-calendar fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Calendar</p>
                   </div>
                </div>
              </div>
           </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-success"  id="postsPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-comments fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Posts</p>
                  </div>
                </div>
              </div>
          </div>
         </div>
</div><!-- /.row -->
<!--Stats & Updates Row 3 -->
<div class="row no-padding">
	<!-- Flot Realtime  -->
               <div class="col-md-8">
                    <div class="panel">
                        <div class="panel-heading">
                            <div class="pull-left"><h4><i class="icon-sitemap"></i> Monthly Traffic Stats</h4></div>
                            <div class="tools pull-right">
                                <a href="#"><i class="icon-refresh text-transparent"></i></a>
                                <a href="javascript:;" class="close-panel" data-dismiss="panel" aria-hidden="true"><i class="icon-remove text-transparent"></i></a>
                             </div>
                             <div class="clearfix"></div>
                        </div>
                        <div class="panel-body no-padding">
                        <!-- realtime chart  -->
                        	<div id="content">
                                <div class="demo-container">
                                    <div id="placeholder" class="demo-placeholder"></div>
                                </div>
                        	</div><!-- / realtime chart  -->
                        
                        </div>
                        <div class="panel-footer">
                        	<a href="#"><small>VIEW ALL</small></a> 
                			<a href="#"><div class="pull-right"><i class="icon-circle-arrow-right"></i></div></a> 
                        </div>
                   </div>
              </div>

    <div class="col-md-4">
        <!-- inner col 1 --><!-- todo -->
        <div class="panel panel-white-solid">
        	<div class="panel-heading">
                    <div class="pull-left">h4><i class="icon-tasks"></i> Todo List</h4></div>
                    <div class="tools pull-right">
                    <a href="#"><i class="icon-refresh text-transparent"></i></a>
                    <a href="javascript:;" class="close-panel" data-dismiss="panel" aria-hidden="true"><i class="icon-remove text-transparent"></i></a>
                    </div>
                    <div class="clearfix"></div>
         	</div>
        	 <div class="panel-body custom-check">
         			<div class="table-responsive table-no-border">
                                 <table id="todo" class="table table-hover custom-check table-striped ">
                                  <tbody>
                                    <tr>
                                        <td class="tools">
                                            <span class="check"><input type="checkbox" class="checked"></span>
                                            <a href="#">Meet with Arin</a>
                                            <a class="close no-padding-right" aria-hidden="true" data-dismiss="alert"><i class="icon-remove"></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-ok text-transparent "></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-pencil text-transparent "></i></a> 
                                            
										</td>
                                        
                                    </tr>
                                    <tr>
                               			<td class="tools">
                                            <span class="check"><input type="checkbox" class="checked"></span>
                                            <a href="#">Send invoice</a>
                                            <a class="close no-padding-right" aria-hidden="true" data-dismiss="alert"><i class="icon-remove"></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-ok text-transparent "></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-pencil text-transparent "></i></a> 
                                            
										</td>
                                    </tr>
                                    <tr>
                               			<td class="tools">
                                            <span class="check"><input type="checkbox" class="checked"></span>
                                            <a href="#">Check messages</a>
                                            <a class="close no-padding-right" aria-hidden="true" data-dismiss="alert"><i class="icon-remove"></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-ok text-transparent "></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-pencil text-transparent "></i></a> 
                                            
										</td>
                                    </tr>
                                    <tr>
                                		<td class="tools">
                                            <span class="check"><input type="checkbox" class="checked"></span>
                                            <a href="#">Pay bills</a>
                                            <a class="close no-padding-right" aria-hidden="true" data-dismiss="alert"><i class="icon-remove"></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-ok text-transparent "></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-pencil text-transparent "></i></a> 
                                            
										</td>
                                    </tr>
                                    <tr>
                                		<td class="tools">
                                            <span class="check"><input type="checkbox" class="checked"></span>
                                            <a href="#">Schedule site </a>
                                            <a class="close no-padding-right" aria-hidden="true" data-dismiss="alert"><i class="icon-remove"></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-ok text-transparent "></i></a>
                                            <a href="#" class="text-transparent pull-right"><i class="icon-pencil text-transparent "></i></a> 
                                            
										</td>
                                     </tr>
                                  </tbody>
                              </table>
                             </div>
         	</div>
                   <div class="panel-footer">
                        <button class="btn btn-inverse btn-xs"><span class="pull-left"><i class="icon-plus"></i>&nbsp;&nbsp;Add Task</span></button>
                        <a href="#"><div class="pull-right text-transparent"><i class="icon-circle-arrow-right"></i></div></a>
                        <div class="clearfix"></div>
                   </div>
         </div>
         <!-- / todo -->
    </div>
</div><!--/ stats & updates row 3 -->
