<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Services\Module'                        => __DIR__ . '/Module.php',
    'Services\Controller\IndexController' => __DIR__ . '/src/Services/Controller/IndexController.php',
    'ServicesTest\Framework\TestCase'        => __DIR__ . '/tests/Services/Framework/TestCase.php',
    'ServicesTest\SampleTest'                => __DIR__ . '/tests/Services/SampleTest.php',
);
