<div class="row">
  <div class="col-lg-12">
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
    </ol>
  </div>
</div>
<div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-info"  id="dashBoardPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-dashboard fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Dashboard</p>
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-warning"  id="productivityPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-bar-chart-o fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Productivity</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-danger"  id="calendarPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-calendar fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Calendar</p>
                   </div>
                </div>
              </div>
           </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-success"  id="postsPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-comments fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Posts</p>
                  </div>
                </div>
              </div>
          </div>
         </div>
</div><!-- /.row -->
						
 <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Teams
                    <a class="btn btn-xs pull-right btn-danger" data-toggle="modal" data-target="#myModal">
                      <i class="fa fa-plus 2x"></i>
                    </a>
                </div>
                <div class="panel-body">
                
                    <div class="row">
                       <ul class="thumbnails list-unstyled">
                          <li class="col-xs-6 col-sm-4 col-md-4">
                            <a href="#" class="thumbnail">
                              <img data-src="holder.js/150x90" alt="150x90" style="width: 150px; height: 90px;" src="mySrc">
                            </a>
                          </li>
                          <li class="col-xs-6 col-sm-4 col-md-4">
                            <a href="#" class="thumbnail">
                              <img data-src="holder.js/150x90" alt="150x90" style="width: 150px; height: 90px;" src="mySrc">
                            </a>
                          </li>
                          <li class="col-xs-6 col-sm-4 col-md-4">
                            <a href="#" class="thumbnail">
                              <img data-src="holder.js/150x90" alt="150x90" style="width: 150px; height: 90px;" src="mySrc">
                            </a>
                          </li>
                          <li class="col-xs-6 col-sm-4 col-md-4">
                            <a href="#" class="thumbnail">
                              <img data-src="holder.js/150x90" alt="150x90" style="width: 150px; height: 90px;" src="mySrc">
                            </a>
                          </li>
                          
                          <li class="col-xs-6 col-sm-4 col-md-4">
                            <a href="#" class="thumbnail">
                              <img data-src="holder.js/150x90" alt="150x90" style="width: 150px; height: 90px;" src="mySrc">
                            </a>
                          </li>
                       </ul>
                     
                    </div>      
                    <ul class="pager">
                        <li class="previous disabled"><a href="#">&larr; Older</a></li>
                        <li class="next"><a href="#">Newer &rarr;</a></li>
                     </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Users
                </div>
                <div class="panel-body">
<!--                     <table class="table table-hover"> -->
<!--                        <thead> -->
<!--                           <tr> -->
<!--                             <th>Page <i class="fa fa-sort"></i></th> -->
<!--                             <th>Members <i class="fa fa-sort"></i></th> -->
<!--                             <th>Growth <i class="fa fa-sort"></i></th> -->
<!--                           </tr> -->
<!--                         </thead> -->
<!--                 <tbody> -->
<!--                   <tr> -->
<!--                     <td>Page 1</td> -->
<!--                     <td>1265</td> -->
<!--                     <td>32.3%</td> -->
<!--                   </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 2</td> -->
<!--                     <td>261</td> -->
<!--                     <td>33.3%</td> -->
<!--                   </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 3</td> -->
<!--                     <td>665</td> -->
<!--                     <td>21.3%</td> -->
<!--                  </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 4</td> -->
<!--                     <td>9516</td> -->
<!--                     <td>89.3%</td> -->
<!--                   </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 5</td> -->
<!--                     <td>23</td> -->
<!--                     <td>34.3%</td> -->
<!--                   </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 6</td> -->
<!--                     <td>421</td> -->
<!--                     <td>60.3%</td> -->
<!--                   </tr> -->
<!--                   <tr> -->
<!--                     <td>Page 7</td> -->
<!--                     <td>1233</td> -->
<!--                     <td>93.2%</td> -->
<!--                   </tr> -->
<!--                 </tbody> -->
<!--               </table> -->
             </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Recent Activity
                </div>
                <div class="panel-body">
                
                    <ul class="list-group">
                        <li class="list-group-item">
                            Activity 1
                        </li>
                        <li class="list-group-item">
                            Activity 2
                        </li>
                        <li class="list-group-item">
                            Activity 3
                        </li>
                        <li class="list-group-item">
                            Activity 4
                        </li>
                        
                    </ul>
                </div>
            </div>
        </div>
</div><!--/row-->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add Team</h4>
      </div>
      <div class="modal-body">
        <?php
            echo $this->form($form,null); 
         ?>     
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
