<div class="row">
  <div class="col-lg-12">
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
    </ol>
  </div>
</div>
<div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-info"  id="dashBoardPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-dashboard fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Dashboard</p>
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-warning"  id="productivityPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-bar-chart-o fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Productivity</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-danger"  id="calendarPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-calendar fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Calendar</p>
                   </div>
                </div>
              </div>
           </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
            <div class="panel panel-success"  id="postsPanel" style="cursor: pointer;">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-comments fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">Posts</p>
                  </div>
                </div>
              </div>
          </div>
         </div>
</div><!-- /.row -->
            
 <div class="row">
       <?php echo $this->partial('dashboard/teamList', array('teams' => $this->teams));?> 
       <?php echo $this->partial('dashboard/memberlist', array('members' => $this->members));?> 
       <?php echo $this->partial('dashboard/testAngularPartial');?>                

</div><!--/row-->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Enter Team Details</h4>
      </div>
      <div class="modal-body">
        <?php
            echo $this->form($form,null); 
         ?>     
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Search User</h4>
      </div>
      <div class="modal-body" id="searchModalBody">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Email Address" name="srch-term" id="srch-term">
            <div class="input-group-btn">
              <button onclick="searchMember()"  class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
       </div>  
      <div  class="modal-footer" id="searchModalFooter">
        
     </div>
    </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


 
