<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Member\Module'                        => __DIR__ . '/Module.php',
    'Member\Controller\IndexController' => __DIR__ . '/src/Member/Controller/IndexController.php',
    'MemberTest\Framework\TestCase'        => __DIR__ . '/tests/Member/Framework/TestCase.php',
    'MemberTest\SampleTest'                => __DIR__ . '/tests/Member/SampleTest.php',
);
