<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Crons\Module'                        => __DIR__ . '/Module.php',
    'Crons\Controller\IndexController' => __DIR__ . '/src/Crons/Controller/IndexController.php',
    'CronsTest\Framework\TestCase'        => __DIR__ . '/tests/Crons/Framework/TestCase.php',
    'CronsTest\SampleTest'                => __DIR__ . '/tests/Crons/SampleTest.php',
);
