<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                        => __DIR__ . '/Module.php',
    'User\Controller\IndexController' => __DIR__ . '/src/User/Controller/IndexController.php',
    'UserTest\Framework\TestCase'        => __DIR__ . '/tests/User/Framework/TestCase.php',
    'UserTest\SampleTest'                => __DIR__ . '/tests/User/SampleTest.php',
);
